apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: ibp-grafana
  namespace: ibp-monitoring
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_password: Password1
      admin_user: admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana