apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.prometheus-_PROJECT_: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus-_PROJECT_"}}'
  labels:
    prometheus: ibp
  name: prometheus-_PROJECT_
  namespace: ibp-monitoring
